name: theologia_app_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  audio_service: ^0.18.18
  audio_session: ^0.2.2
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  firebase_remote_config: ^6.2.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^20.1.0
  flutter_svg: ^2.2.3
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  google_sign_in: ^7.2.0
  intl: ^0.20.2
  just_audio: ^0.10.5
  package_info_plus: ^9.0.0
  sign_in_with_apple: ^7.0.1
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_launcher_icon.png"

  adaptive_icon_foreground: "assets/App_Icon_Android_Foreground.png"
  adaptive_icon_background: "#b69260"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/theologia-logo.png
  fonts:

    # -------------------------
    # Work Sans (UI Font)
    # -------------------------
    - family: WorkSans
      fonts:
        - asset: assets/fonts/worksans/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/worksans/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/worksans/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/worksans/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/worksans/WorkSans-Black.ttf
          weight: 900

    # -------------------------
    # Lora (Serif / Devotion Font)
    # -------------------------
    - family: Lora
      fonts:
        - asset: assets/fonts/lora/Lora-Regular.ttf
          weight: 400
        - asset: assets/fonts/lora/Lora-Medium.ttf
          weight: 500
        - asset: assets/fonts/lora/Lora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/lora/Lora-Bold.ttf
          weight: 700
        - asset: assets/fonts/lora/Lora-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/lora/Lora-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/lora/Lora-BoldItalic.ttf
          weight: 700
          style: italic


