// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoM6nSLOgw865465ImkKQLskmzF-gI66Y',
    appId: '1:910435159609:web:1aa436fd9827e6c4d607e8',
    messagingSenderId: '910435159609',
    projectId: 'theologia-2a39d',
    authDomain: 'theologia-2a39d.firebaseapp.com',
    storageBucket: 'theologia-2a39d.firebasestorage.app',
    measurementId: 'G-2BWQYC6WQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb6GzM3-vgTKRDFqcCQIKSlX59FYplPI4',
    appId: '1:910435159609:android:510f638e1de01500d607e8',
    messagingSenderId: '910435159609',
    projectId: 'theologia-2a39d',
    storageBucket: 'theologia-2a39d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_uucb7x1a6hYDj0WAE7V6AYowVGbQ_fc',
    appId: '1:910435159609:ios:1eb376ecc37d9b73d607e8',
    messagingSenderId: '910435159609',
    projectId: 'theologia-2a39d',
    storageBucket: 'theologia-2a39d.firebasestorage.app',
    androidClientId: '910435159609-ad1itu1m03g2ih9dnmd34l6m3va26j1q.apps.googleusercontent.com',
    iosClientId: '910435159609-4k6d60vv60e6lso32v95qcrqqgl7n78h.apps.googleusercontent.com',
    iosBundleId: 'com.redmediasolutions.theologiaapp',
  );
}
